# -*- coding: utf-8 -*-
from bs4 import BeautifulSoup

# 示例 HTML
html_content = """
<div><div id="question-5211145-1" class="que essay manualgraded complete"><div class="info"><h3 class="no">试题 <span class="qno">1</span></h3><div class="state">完成</div><div class="grade">满分10.0</div><div class="questionflag editable" id="yui_3_18_1_1_1734005620375_22"><input type="hidden" name="q5211145:1_:flagged" value="0"><input type="hidden" value="qaid=71182735&amp;qubaid=5211145&amp;qid=6812294&amp;slot=1&amp;checksum=e9eabfe2043afb48e0b32c5ce987a72b&amp;sesskey=anKk6RDGic&amp;newstate=" class="questionflagpostdata">
<input type="hidden" class="questionflagvalue" id="q5211145:1_:flaggedcheckbox" name="q5211145:1_:flagged" value="0"><a tabindex="0" class="aabtn" role="button" aria-pressed="false" aria-label="已标记" title="标记此试题供将来参考"><img class="questionflagimage" src="https://moodle.scnu.edu.cn/theme/image.php/lambda2/core/1733950803/i/unflagged" alt="">标记试题</a></div></div><div class="content"><div class="formulation clearfix"><h4 class="accesshide">试题正文</h4><input type="hidden" name="q5211145:1_:sequencecheck" value="3"><div class="qtext"><p dir="ltr" style="text-align: left;">请简要谈谈自己对科技与工程伦理教育的认识。<br></p></div><div class="ablock"><div class="answer"><h4 id="q5211145:1_answer_label" class="sr-only">答案文本 试题 1</h4><div role="textbox" aria-readonly="true" aria-labelledby="q5211145:1_answer_label" class="qtype_essay_editor qtype_essay_response readonly" style="min-height: 15em;"><p dir="ltr" style="text-align:left;"></p><p>科技与工程伦理教育是培养学生与专业人士在科技与工程实践中进行伦理决策能力的重要领域。其核心内容包括：</p><p>首先，培养责任意识，使学生认识到在设计与实施技术时对社会、环境和公众健康的潜在影响。其次，通过建立价值观与决策框架，帮助学生理解不同价值观之间的冲突，从而在道德困境中做出明智选择。此外，案例研究的应用让学生通过分析历史伦理案例，学习处理实际问题的技巧，并从他人经验中汲取教训。</p><p>再者，伦理教育强调跨学科视角，涵盖社会科学、法律与政策等领域，促进综合思考能力的提升。最后，随着科技的快速发展，伦理教育需不断更新，以培养终身学习的态度，使专业人士能够适应新的挑战与道德问题。</p><p>综上所述，科技与工程伦理教育不仅提升了个人的道德素养，也为社会的可持续发展贡献了积极力量。</p><br><p></p></div></div><div class="attachments"></div></div></div></div></div><div id="question-5211145-2" class="que multichoice deferredfeedback correct"><div class="info"><h3 class="no">试题 <span class="qno">2</span></h3><div class="state">正确</div><div class="grade">得分 1.0/1.0 分</div><div class="questionflag editable" id="yui_3_18_1_1_1734005620375_28"><input type="hidden" name="q5211145:2_:flagged" value="0"><input type="hidden" value="qaid=71182736&amp;qubaid=5211145&amp;qid=6812295&amp;slot=2&amp;checksum=2be5b906e2eae1626a55de5b1bd90e03&amp;sesskey=anKk6RDGic&amp;newstate=" class="questionflagpostdata">
<input type="hidden" class="questionflagvalue" id="q5211145:2_:flaggedcheckbox" name="q5211145:2_:flagged" value="0"><a tabindex="0" class="aabtn" role="button" aria-pressed="false" aria-label="已标记" title="标记此试题供将来参考"><img class="questionflagimage" src="https://moodle.scnu.edu.cn/theme/image.php/lambda2/core/1733950803/i/unflagged" alt="">标记试题</a></div></div><div class="content"><div class="formulation clearfix"><h4 class="accesshide">试题正文</h4><input type="hidden" name="q5211145:2_:sequencecheck" value="3"><div class="qtext">中共中央办公厅、国务院办公厅在2022年3月印发了《关于加强科技伦理治理的意见》，包含以下哪些治理要求？
①伦理先行②依法依规③敏捷治理④立足国情⑤开放合作</div><fieldset class="ablock no-overflow visual-scroll-x"><legend class="prompt h6 font-weight-normal sr-only"><span class="sr-only">试题 2</span> 回答</legend><div class="answer"><div class="r0"><input type="radio" name="q5211145:2_answer" disabled="disabled" value="0" id="q5211145:2_answer0" aria-labelledby="q5211145:2_answer0_label"><div class="d-flex w-auto" id="q5211145:2_answer0_label" data-region="answer-label"><span class="answernumber">A. </span><div class="flex-fill ml-1">①③④⑤</div></div> </div>
<div class="r1"><input type="radio" name="q5211145:2_answer" disabled="disabled" value="1" id="q5211145:2_answer1" aria-labelledby="q5211145:2_answer1_label"><div class="d-flex w-auto" id="q5211145:2_answer1_label" data-region="answer-label"><span class="answernumber">B. </span><div class="flex-fill ml-1">①②③④</div></div> </div>
<div class="r0"><input type="radio" name="q5211145:2_answer" disabled="disabled" value="2" id="q5211145:2_answer2" aria-labelledby="q5211145:2_answer2_label"><div class="d-flex w-auto" id="q5211145:2_answer2_label" data-region="answer-label"><span class="answernumber">C. </span><div class="flex-fill ml-1">①②③⑤</div></div> </div>
<div class="r1 correct"><input type="radio" name="q5211145:2_answer" disabled="disabled" value="3" id="q5211145:2_answer3" aria-labelledby="q5211145:2_answer3_label" checked="checked"><div class="d-flex w-auto" id="q5211145:2_answer3_label" data-region="answer-label"><span class="answernumber">D. </span><div class="flex-fill ml-1">①②③④⑤</div></div> <span class="ml-1"><i class="icon fa fa-check text-success fa-fw " title="正确" role="img" aria-label="正确"></i></span></div>
</div></fieldset></div><div class="outcome clearfix"><h4 class="accesshide">反馈</h4><div class="feedback"><div class="rightanswer">正确答案是：①②③④⑤</div></div></div></div></div><div id="question-5211145-3" class="que multichoice deferredfeedback correct"><div class="info"><h3 class="no">试题 <span class="qno">3</span></h3><div class="state">正确</div><div class="grade">得分 1.0/1.0 分</div><div class="questionflag editable" id="yui_3_18_1_1_1734005620375_34"><input type="hidden" name="q5211145:3_:flagged" value="0"><input type="hidden" value="qaid=71182737&amp;qubaid=5211145&amp;qid=6812296&amp;slot=3&amp;checksum=9557ccc5ac3038184427b8ed55589528&amp;sesskey=anKk6RDGic&amp;newstate=" class="questionflagpostdata">
<input type="hidden" class="questionflagvalue" id="q5211145:3_:flaggedcheckbox" name="q5211145:3_:flagged" value="0"><a tabindex="0" class="aabtn" role="button" aria-pressed="false" aria-label="已标记" title="标记此试题供将来参考"><img class="questionflagimage" src="https://moodle.scnu.edu.cn/theme/image.php/lambda2/core/1733950803/i/unflagged" alt="">标记试题</a></div></div><div class="content"><div class="formulation clearfix"><h4 class="accesshide">试题正文</h4><input type="hidden" name="q5211145:3_:sequencecheck" value="3"><div class="qtext">伦理原则是最基本的__________和____________, 给科技活动全过程的行为规范起到了指导性的作用。</div><fieldset class="ablock no-overflow visual-scroll-x"><legend class="prompt h6 font-weight-normal sr-only"><span class="sr-only">试题 3</span> 回答</legend><div class="answer"><div class="r0 correct"><input type="radio" name="q5211145:3_answer" disabled="disabled" value="0" id="q5211145:3_answer0" aria-labelledby="q5211145:3_answer0_label" checked="checked"><div class="d-flex w-auto" id="q5211145:3_answer0_label" data-region="answer-label"><span class="answernumber">A. </span><div class="flex-fill ml-1">价值取向；道德规范</div></div> <span class="ml-1"><i class="icon fa fa-check text-success fa-fw " title="正确" role="img" aria-label="正确"></i></span></div>
<div class="r1"><input type="radio" name="q5211145:3_answer" disabled="disabled" value="1" id="q5211145:3_answer1" aria-labelledby="q5211145:3_answer1_label"><div class="d-flex w-auto" id="q5211145:3_answer1_label" data-region="answer-label"><span class="answernumber">B. </span><div class="flex-fill ml-1">客观标准；道德标准</div></div> </div>
<div class="r0"><input type="radio" name="q5211145:3_answer" disabled="disabled" value="2" id="q5211145:3_answer2" aria-labelledby="q5211145:3_answer2_label"><div class="d-flex w-auto" id="q5211145:3_answer2_label" data-region="answer-label"><span class="answernumber">C. </span><div class="flex-fill ml-1">道德标准；道德规范</div></div> </div>
<div class="r1"><input type="radio" name="q5211145:3_answer" disabled="disabled" value="3" id="q5211145:3_answer3" aria-labelledby="q5211145:3_answer3_label"><div class="d-flex w-auto" id="q5211145:3_answer3_label" data-region="answer-label"><span class="answernumber">D. </span><div class="flex-fill ml-1">价值标准；行为规范</div></div> </div>
</div></fieldset></div><div class="outcome clearfix"><h4 class="accesshide">反馈</h4><div class="feedback"><div class="rightanswer">正确答案是：价值取向；道德规范</div></div></div></div></div><div id="question-5211145-4" class="que multichoice deferredfeedback incorrect"><div class="info"><h3 class="no">试题 <span class="qno">4</span></h3><div class="state">错误</div><div class="grade">得分 0.0/1.0 分</div><div class="questionflag editable" id="yui_3_18_1_1_1734005620375_40"><input type="hidden" name="q5211145:4_:flagged" value="0"><input type="hidden" value="qaid=71182738&amp;qubaid=5211145&amp;qid=6812297&amp;slot=4&amp;checksum=1d53ce444b20fdc01f8eea58be88c2f3&amp;sesskey=anKk6RDGic&amp;newstate=" class="questionflagpostdata">
<input type="hidden" class="questionflagvalue" id="q5211145:4_:flaggedcheckbox" name="q5211145:4_:flagged" value="0"><a tabindex="0" class="aabtn" role="button" aria-pressed="false" aria-label="已标记" title="标记此试题供将来参考"><img class="questionflagimage" src="https://moodle.scnu.edu.cn/theme/image.php/lambda2/core/1733950803/i/unflagged" alt="">标记试题</a></div></div><div class="content"><div class="formulation clearfix"><h4 class="accesshide">试题正文</h4><input type="hidden" name="q5211145:4_:sequencecheck" value="3"><div class="qtext">在科技伦理治理中，科技发展的根本目的是什么？</div><fieldset class="ablock no-overflow visual-scroll-x"><legend class="prompt h6 font-weight-normal sr-only"><span class="sr-only">试题 4</span> 回答</legend><div class="answer"><div class="r0"><input type="radio" name="q5211145:4_answer" disabled="disabled" value="0" id="q5211145:4_answer0" aria-labelledby="q5211145:4_answer0_label"><div class="d-flex w-auto" id="q5211145:4_answer0_label" data-region="answer-label"><span class="answernumber">A. </span><div class="flex-fill ml-1">促进经济社会发展</div></div> </div>
<div class="r1 incorrect"><input type="radio" name="q5211145:4_answer" disabled="disabled" value="1" id="q5211145:4_answer1" aria-labelledby="q5211145:4_answer1_label" checked="checked"><div class="d-flex w-auto" id="q5211145:4_answer1_label" data-region="answer-label"><span class="answernumber">B. </span><div class="flex-fill ml-1">改造自然环境</div></div> <span class="ml-1"><i class="icon fa fa-remove text-danger fa-fw " title="错误" role="img" aria-label="错误"></i></span></div>
<div class="r0"><input type="radio" name="q5211145:4_answer" disabled="disabled" value="2" id="q5211145:4_answer2" aria-labelledby="q5211145:4_answer2_label"><div class="d-flex w-auto" id="q5211145:4_answer2_label" data-region="answer-label"><span class="answernumber">C. </span><div class="flex-fill ml-1">获得真理知识</div></div> </div>
<div class="r1"><input type="radio" name="q5211145:4_answer" disabled="disabled" value="3" id="q5211145:4_answer3" aria-labelledby="q5211145:4_answer3_label"><div class="d-flex w-auto" id="q5211145:4_answer3_label" data-region="answer-label"><span class="answernumber">D. </span><div class="flex-fill ml-1">增进人类福祉</div></div> </div>
</div></fieldset></div></div></div><div id="question-5211145-5" class="que multichoiceset deferredfeedback correct"><div class="info"><h3 class="no">试题 <span class="qno">5</span></h3><div class="state">正确</div><div class="grade">得分 2.0/2.0 分</div><div class="questionflag editable" id="yui_3_18_1_1_1734005620375_46"><input type="hidden" name="q5211145:5_:flagged" value="0"><input type="hidden" value="qaid=71182739&amp;qubaid=5211145&amp;qid=6812298&amp;slot=5&amp;checksum=91141bef3fa4d635be5a268e4ec742cf&amp;sesskey=anKk6RDGic&amp;newstate=" class="questionflagpostdata">
<input type="hidden" class="questionflagvalue" id="q5211145:5_:flaggedcheckbox" name="q5211145:5_:flagged" value="0"><a tabindex="0" class="aabtn" role="button" aria-pressed="false" aria-label="已标记" title="标记此试题供将来参考"><img class="questionflagimage" src="https://moodle.scnu.edu.cn/theme/image.php/lambda2/core/1733950803/i/unflagged" alt="">标记试题</a></div></div><div class="content"><div class="formulation clearfix"><h4 class="accesshide">试题正文</h4><input type="hidden" name="q5211145:5_:sequencecheck" value="3"><div class="qtext">面对大数据技术在人类社会的应用使个人的隐私权受到威胁这一问题，《关于加强科技伦理治理的意见》要求我们应该遵循_____原则。</div><fieldset class="ablock no-overflow visual-scroll-x"><legend class="prompt h6 font-weight-normal "><span class="sr-only">试题 5</span> 选择一项或多项：</legend><div class="answer"><div class="r0 correct"><input type="checkbox" name="q5211145:5_choice0" disabled="disabled" value="1" id="q5211145:5_choice0" aria-labelledby="q5211145:5_choice0_label" checked="checked"><div class="d-flex w-auto" id="q5211145:5_choice0_label" data-region="answer-label"><span class="answernumber">A. </span><div class="flex-fill ml-1">尊重生命权利</div></div> <span class="ml-1"><i class="icon fa fa-check text-success fa-fw " title="正确" role="img" aria-label="正确"></i></span></div>
<div class="r1 correct"><input type="checkbox" name="q5211145:5_choice1" disabled="disabled" value="1" id="q5211145:5_choice1" aria-labelledby="q5211145:5_choice1_label" checked="checked"><div class="d-flex w-auto" id="q5211145:5_choice1_label" data-region="answer-label"><span class="answernumber">B. </span><div class="flex-fill ml-1">保持公开透明</div></div> <span class="ml-1"><i class="icon fa fa-check text-success fa-fw " title="正确" role="img" aria-label="正确"></i></span></div>
<div class="r0 correct"><input type="checkbox" name="q5211145:5_choice2" disabled="disabled" value="1" id="q5211145:5_choice2" aria-labelledby="q5211145:5_choice2_label" checked="checked"><div class="d-flex w-auto" id="q5211145:5_choice2_label" data-region="answer-label"><span class="answernumber">C. </span><div class="flex-fill ml-1">增进人类福祉</div></div> <span class="ml-1"><i class="icon fa fa-check text-success fa-fw " title="正确" role="img" aria-label="正确"></i></span></div>
<div class="r1 correct"><input type="checkbox" name="q5211145:5_choice3" disabled="disabled" value="1" id="q5211145:5_choice3" aria-labelledby="q5211145:5_choice3_label" checked="checked"><div class="d-flex w-auto" id="q5211145:5_choice3_label" data-region="answer-label"><span class="answernumber">D. </span><div class="flex-fill ml-1">坚持公平公正</div></div> <span class="ml-1"><i class="icon fa fa-check text-success fa-fw " title="正确" role="img" aria-label="正确"></i></span></div>
</div></fieldset></div><div class="outcome clearfix"><h4 class="accesshide">反馈</h4><div class="feedback"><div class="rightanswer">正确答案是：增进人类福祉, 尊重生命权利, 坚持公平公正, 保持公开透明</div></div></div></div></div><input type="hidden" name="sesskey" value="anKk6RDGic"><div class="submitbtns"></div></div>
"""

# 解析 HTML
soup = BeautifulSoup(html_content, 'html.parser')

# 提取所有 class 为 qtext 的 div 标签文本
div_texts = [div.get_text() for div in soup.find_all('div', class_='qtext')]

# 添加序号并按行输出
output = '\n'.join(f"{i + 1}. {text}" for i, text in enumerate(div_texts))
print(output)
